// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcknfcivisnizfuktsgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJja25mY2l2aXNuaXpmdWt0c2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ5NzksImV4cCI6MjA2OTM3MDk3OX0.TzTnfjz1qWqkfE-cJGVu5DJoYK1f62AnSD3WzGLfJg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});